# Generated by Django 4.1.7 on 2023-02-19 01:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("apps_api", "0001_api_models"),
    ]

    operations = [
        migrations.AlterField(
            model_name="personcitizen",
            name="email_person",
            field=models.EmailField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name="personofficer",
            name="personal_id",
            field=models.IntegerField(unique=True),
        ),
        migrations.AlterField(
            model_name="vehicle",
            name="brand",
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name="vehicle",
            name="color",
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
    ]
